import XCTest
import PostgresKit
@testable import Echo

/// Tests PostgreSQL Phase 3 table designer features through Echo's DatabaseSession layer.
/// Verifies that identity columns, collation, check constraints, index types, INCLUDE columns,
/// deferrable constraints, and table properties all round-trip correctly through
/// `getTableStructureDetails`.
final class PGTableDesignerTests: PostgresDockerTestCase {

    // MARK: - Identity Columns

    func testIdentityColumnAlways() async throws {
        let tableName = uniqueName()
        try await execute("""
            CREATE TABLE public.\(tableName) (
                id INT GENERATED ALWAYS AS IDENTITY,
                name TEXT
            )
        """)
        cleanupSQL("DROP TABLE IF EXISTS public.\(tableName)")

        let details = try await session.getTableStructureDetails(schema: "public", table: tableName)
        let idColumn = try XCTUnwrap(details.columns.first(where: { $0.name == "id" }))
        XCTAssertTrue(idColumn.isIdentity, "id column should be an identity column")
        XCTAssertEqual(idColumn.identityGeneration, "ALWAYS", "Identity generation should be ALWAYS")
    }

    func testIdentityColumnByDefault() async throws {
        let tableName = uniqueName()
        try await execute("""
            CREATE TABLE public.\(tableName) (
                id INT GENERATED BY DEFAULT AS IDENTITY,
                name TEXT
            )
        """)
        cleanupSQL("DROP TABLE IF EXISTS public.\(tableName)")

        let details = try await session.getTableStructureDetails(schema: "public", table: tableName)
        let idColumn = try XCTUnwrap(details.columns.first(where: { $0.name == "id" }))
        XCTAssertTrue(idColumn.isIdentity, "id column should be an identity column")
        XCTAssertEqual(idColumn.identityGeneration, "BY DEFAULT", "Identity generation should be BY DEFAULT")
    }

    // MARK: - Collation

    func testColumnCollation() async throws {
        let tableName = uniqueName()
        try await execute("""
            CREATE TABLE public.\(tableName) (
                id SERIAL PRIMARY KEY,
                name TEXT COLLATE "C"
            )
        """)
        cleanupSQL("DROP TABLE IF EXISTS public.\(tableName)")

        let details = try await session.getTableStructureDetails(schema: "public", table: tableName)
        let nameColumn = try XCTUnwrap(details.columns.first(where: { $0.name == "name" }))
        XCTAssertNotNil(nameColumn.collation, "Collation should not be nil for column with explicit COLLATE")
        XCTAssertEqual(nameColumn.collation, "C", "Collation should be 'C'")
    }

    // MARK: - Check Constraints

    func testCheckConstraintIntrospection() async throws {
        let tableName = uniqueName()
        try await execute("""
            CREATE TABLE public.\(tableName) (
                id SERIAL PRIMARY KEY,
                value INT NOT NULL,
                CONSTRAINT ck_positive CHECK (value > 0)
            )
        """)
        cleanupSQL("DROP TABLE IF EXISTS public.\(tableName)")

        let details = try await session.getTableStructureDetails(schema: "public", table: tableName)
        XCTAssertEqual(details.checkConstraints.count, 1, "Should have exactly one check constraint")
        let ck = details.checkConstraints[0]
        XCTAssertEqual(ck.name, "ck_positive", "Check constraint name should match")
        XCTAssertTrue(ck.expression.contains("value > 0"), "Expression should contain 'value > 0', got: \(ck.expression)")
    }

    func testMultipleCheckConstraints() async throws {
        let tableName = uniqueName()
        try await execute("""
            CREATE TABLE public.\(tableName) (
                id SERIAL PRIMARY KEY,
                value INT NOT NULL,
                status TEXT NOT NULL,
                CONSTRAINT ck_positive CHECK (value > 0),
                CONSTRAINT ck_status CHECK (status IN ('active', 'inactive'))
            )
        """)
        cleanupSQL("DROP TABLE IF EXISTS public.\(tableName)")

        let details = try await session.getTableStructureDetails(schema: "public", table: tableName)
        XCTAssertEqual(details.checkConstraints.count, 2, "Should have two check constraints")
        let names = Set(details.checkConstraints.map(\.name))
        XCTAssertTrue(names.contains("ck_positive"), "Should contain ck_positive")
        XCTAssertTrue(names.contains("ck_status"), "Should contain ck_status")
    }

    // MARK: - Index Type and INCLUDE

    func testIndexTypeGin() async throws {
        let tableName = uniqueName()
        let indexName = uniqueName(prefix: "idx")
        try await execute("""
            CREATE TABLE public.\(tableName) (
                id SERIAL PRIMARY KEY,
                data JSONB NOT NULL
            )
        """)
        try await execute("CREATE INDEX \(indexName) ON public.\(tableName) USING gin (data)")
        cleanupSQL("DROP TABLE IF EXISTS public.\(tableName)")

        let details = try await session.getTableStructureDetails(schema: "public", table: tableName)
        let ginIndex = details.indexes.first(where: { $0.name == indexName })
        let idx = try XCTUnwrap(ginIndex, "GIN index should be present in table details")
        XCTAssertEqual(idx.indexType?.lowercased(), "gin", "Index type should be 'gin', got: \(idx.indexType ?? "nil")")
    }

    func testIndexWithIncludeColumns() async throws {
        let tableName = uniqueName()
        let indexName = uniqueName(prefix: "idx")
        try await execute("""
            CREATE TABLE public.\(tableName) (
                id SERIAL PRIMARY KEY,
                key_col INT NOT NULL,
                included_col TEXT
            )
        """)
        try await execute("CREATE INDEX \(indexName) ON public.\(tableName) (key_col) INCLUDE (included_col)")
        cleanupSQL("DROP TABLE IF EXISTS public.\(tableName)")

        let details = try await session.getTableStructureDetails(schema: "public", table: tableName)
        let idx = try XCTUnwrap(details.indexes.first(where: { $0.name == indexName }), "Index should be present")
        XCTAssertGreaterThanOrEqual(idx.columns.count, 2, "Index should have at least 2 columns (key + include)")

        let keyCol = idx.columns.first(where: { $0.name == "key_col" })
        let inclCol = idx.columns.first(where: { $0.name == "included_col" })
        XCTAssertNotNil(keyCol, "Key column should be present")
        XCTAssertNotNil(inclCol, "Included column should be present")
        XCTAssertFalse(keyCol?.isIncluded ?? true, "Key column should not be marked as included")
        XCTAssertTrue(inclCol?.isIncluded ?? false, "Included column should be marked as included")
    }

    // MARK: - Deferrable Constraints

    func testDeferrableForeignKey() async throws {
        let parentTable = uniqueName(prefix: "parent")
        let childTable = uniqueName(prefix: "child")
        try await execute("""
            CREATE TABLE public.\(parentTable) (
                id SERIAL PRIMARY KEY
            )
        """)
        try await execute("""
            CREATE TABLE public.\(childTable) (
                id SERIAL PRIMARY KEY,
                parent_id INT NOT NULL,
                CONSTRAINT fk_parent FOREIGN KEY (parent_id)
                    REFERENCES public.\(parentTable)(id)
                    DEFERRABLE INITIALLY DEFERRED
            )
        """)
        cleanupSQL(
            "DROP TABLE IF EXISTS public.\(childTable)",
            "DROP TABLE IF EXISTS public.\(parentTable)"
        )

        let details = try await session.getTableStructureDetails(schema: "public", table: childTable)
        let fk = try XCTUnwrap(details.foreignKeys.first(where: { $0.name == "fk_parent" }), "FK should be present")
        XCTAssertTrue(fk.isDeferrable, "FK should be deferrable")
        XCTAssertTrue(fk.isInitiallyDeferred, "FK should be initially deferred")
    }

    func testNonDeferrableForeignKey() async throws {
        let parentTable = uniqueName(prefix: "parent")
        let childTable = uniqueName(prefix: "child")
        try await execute("""
            CREATE TABLE public.\(parentTable) (
                id SERIAL PRIMARY KEY
            )
        """)
        try await execute("""
            CREATE TABLE public.\(childTable) (
                id SERIAL PRIMARY KEY,
                parent_id INT NOT NULL,
                CONSTRAINT fk_parent FOREIGN KEY (parent_id)
                    REFERENCES public.\(parentTable)(id)
            )
        """)
        cleanupSQL(
            "DROP TABLE IF EXISTS public.\(childTable)",
            "DROP TABLE IF EXISTS public.\(parentTable)"
        )

        let details = try await session.getTableStructureDetails(schema: "public", table: childTable)
        let fk = try XCTUnwrap(details.foreignKeys.first(where: { $0.name == "fk_parent" }), "FK should be present")
        XCTAssertFalse(fk.isDeferrable, "Regular FK should not be deferrable")
        XCTAssertFalse(fk.isInitiallyDeferred, "Regular FK should not be initially deferred")
    }

    func testDeferrableUniqueConstraint() async throws {
        let tableName = uniqueName()
        try await execute("""
            CREATE TABLE public.\(tableName) (
                id SERIAL PRIMARY KEY,
                code TEXT NOT NULL,
                CONSTRAINT uq_code UNIQUE (code) DEFERRABLE INITIALLY DEFERRED
            )
        """)
        cleanupSQL("DROP TABLE IF EXISTS public.\(tableName)")

        let details = try await session.getTableStructureDetails(schema: "public", table: tableName)
        let uq = try XCTUnwrap(details.uniqueConstraints.first(where: { $0.name == "uq_code" }), "Unique constraint should be present")
        XCTAssertTrue(uq.isDeferrable, "Unique constraint should be deferrable")
        XCTAssertTrue(uq.isInitiallyDeferred, "Unique constraint should be initially deferred")
    }

    func testDeferrablePrimaryKey() async throws {
        let tableName = uniqueName()
        try await execute("""
            CREATE TABLE public.\(tableName) (
                id INT NOT NULL,
                CONSTRAINT pk_def PRIMARY KEY (id) DEFERRABLE INITIALLY IMMEDIATE
            )
        """)
        cleanupSQL("DROP TABLE IF EXISTS public.\(tableName)")

        let details = try await session.getTableStructureDetails(schema: "public", table: tableName)
        let pk = try XCTUnwrap(details.primaryKey, "Primary key should be present")
        XCTAssertTrue(pk.isDeferrable, "PK should be deferrable")
        XCTAssertFalse(pk.isInitiallyDeferred, "PK should not be initially deferred (INITIALLY IMMEDIATE)")
    }

    // MARK: - Table Properties

    func testTablePropertiesFillfactor() async throws {
        let tableName = uniqueName()
        try await execute("""
            CREATE TABLE public.\(tableName) (
                id SERIAL PRIMARY KEY,
                name TEXT
            ) WITH (fillfactor = 80)
        """)
        cleanupSQL("DROP TABLE IF EXISTS public.\(tableName)")

        let details = try await session.getTableStructureDetails(schema: "public", table: tableName)
        let props = try XCTUnwrap(details.tableProperties, "Table properties should not be nil")
        XCTAssertEqual(props.fillfactor, 80, "Fillfactor should be 80")
    }

    func testTablePropertiesDefault() async throws {
        let tableName = uniqueName()
        try await execute("""
            CREATE TABLE public.\(tableName) (
                id SERIAL PRIMARY KEY,
                name TEXT
            )
        """)
        cleanupSQL("DROP TABLE IF EXISTS public.\(tableName)")

        let details = try await session.getTableStructureDetails(schema: "public", table: tableName)
        XCTAssertNotNil(details.tableProperties, "Table properties should not be nil even for default table")
    }
}
