import Foundation
import Logging
import SQLServerKit

extension GenerateScriptsWizardViewModel {
    func generate() {
        isGenerating = true
        progress = 0
        statusMessage = "Preparing script..."
        generationError = nil
        generationSucceeded = false
        let db = databaseName
        let databaseType = self.databaseType
        let options = SQLServerScriptingOptions(
            scriptMode: scriptMode,
            includePermissions: includePermissions,
            includeTriggers: includeTriggers,
            includeIndexes: includeIndexes,
            includeExtendedProperties: includeExtendedProperties,
            checkExistence: checkExistence,
            scriptDropAndCreate: scriptDropAndCreate,
            includeUseDatabase: includeUseDatabase
        )
        let allObjects = objectsByCategory.flatMap(\.objects)
        let session = self.session
        let logger = self.logger

        Task { [db, databaseType, options, allObjects, session, logger] in
            do {
                let selectedObjects = try await self.selectedObjectsForGeneration(from: allObjects, session: session)
                var script = "-- Generated by Echo on \(Date().formatted())\n"
                script += GenerateScriptsScriptBuilder.preamble(
                    databaseName: db,
                    databaseType: databaseType,
                    includeUseDatabase: options.includeUseDatabase
                )

                let totalSteps = Double(selectedObjects.count + dataScriptObjectCount(in: selectedObjects, mode: options.scriptMode))
                var completedSteps = 0.0

                if options.scriptMode != .dataOnly {
                    for object in selectedObjects {
                        self.statusMessage = "Scripting \(object.qualifiedName)..."
                        if let definition = try await self.definition(for: object, databaseName: db, session: session) {
                            let body = GenerateScriptsScriptBuilder.wrappedDefinition(
                                definition,
                                object: object,
                                databaseType: databaseType,
                                checkExistence: options.checkExistence,
                                scriptDropAndCreate: options.scriptDropAndCreate
                            )
                            script += body + "\n\n"
                        }
                        completedSteps += 1
                        self.progress = completedSteps / max(totalSteps, 1)
                    }
                }

                if options.scriptMode != .schemaOnly {
                    let dataObjects = selectedObjects.filter { $0.type == .table }
                    for object in dataObjects {
                        self.statusMessage = "Extracting rows from \(object.qualifiedName)..."
                        let result = try await session.simpleQuery(
                            GenerateScriptsScriptBuilder.dataSelectSQL(for: object, databaseType: databaseType)
                        )
                        let inserts = GenerateScriptsScriptBuilder.insertStatements(
                            for: result,
                            object: object,
                            databaseType: databaseType
                        )
                        script += "-- Data for \(object.qualifiedName)\n"
                        script += inserts + "\n\n"
                        completedSteps += 1
                        self.progress = completedSteps / max(totalSteps, 1)
                    }
                }

                self.generatedScript = script
                self.statusMessage = "Script generation complete."
                self.isGenerating = false
                self.generationSucceeded = true
                self.deliverOutput(script)
            } catch {
                logger.error("Script generation failed: \(error)")
                self.generationError = error.localizedDescription
                self.statusMessage = "Error: \(error.localizedDescription)"
                self.isGenerating = false
            }
        }
    }

    private func selectedObjectsForGeneration(
        from objects: [GenerateScriptsObject],
        session: DatabaseSession
    ) async throws -> [GenerateScriptsObject] {
        let allObjects = try await orderedObjectsForCurrentDialect(from: objects, session: session)
        return GenerateScriptsScriptBuilder.objectGenerationOrder(
            from: allObjects,
            selectedObjectIDs: selectedObjectIDs,
            includeTriggers: includeTriggers
        )
    }

    private func definition(
        for object: GenerateScriptsObject,
        databaseName: String,
        session: DatabaseSession
    ) async throws -> String? {
        if let deps = session.dependencies {
            return try await deps.scriptObjectDDL(
                database: databaseName,
                schema: object.schema,
                name: object.name,
                objectType: GenerateScriptsScriptBuilder.sqlServerTypeCode(for: object.type)
            )
        }

        return try await session.getObjectDefinition(
            objectName: object.name,
            schemaName: object.schema,
            objectType: object.type,
            database: databaseName
        )
    }

    private func orderedObjectsForCurrentDialect(
        from objects: [GenerateScriptsObject],
        session: DatabaseSession
    ) async throws -> [GenerateScriptsObject] {
        guard let dependencies = session.dependencies else {
            return objects
        }

        let graph = try await dependencies.buildGraph(database: databaseName)
        let objectMap = Dictionary(uniqueKeysWithValues: objects.map { ($0.id, $0) })
        let ordered = graph.resolvedOrder().compactMap { sqlObject -> GenerateScriptsObject? in
            guard let type = Self.objectType(forSQLServerTypeCode: sqlObject.type) else {
                return nil
            }
            let objectID = GenerateScriptsObject(schema: sqlObject.schema, name: sqlObject.name, type: type).id
            return objectMap[objectID]
        }
        if ordered.count == objects.count {
            return ordered
        }

        let orderedIDs = Set(ordered.map { $0.id })
        return ordered + objects.filter { !orderedIDs.contains($0.id) }
    }

    private func dataScriptObjectCount(in objects: [GenerateScriptsObject], mode: SQLServerScriptingOptions.ScriptMode) -> Int {
        guard mode != .schemaOnly else { return 0 }
        return objects.filter { $0.type == .table }.count
    }
}
