import Foundation
import Observation
import SQLServerKit
import Logging

@Observable @MainActor
final class GenerateScriptsWizardViewModel {
    enum Step: Int, CaseIterable {
        case selectObjects = 1
        case setOptions = 2
        case outputDestination = 3
        case summary = 4
    }
    
    var currentStep: Step = .selectObjects
    var objects: [SQLServerObjectIdentifier] = []
    var selectedObjectIDs: Set<SQLServerObjectIdentifier> = []
    var isLoadingObjects = false
    
    // Options
    var scriptData = false
    var includeDependencies = true
    var checkForExistence = true
    var scriptDropAndCreate = false
    
    // Output
    enum Destination: String, CaseIterable, Identifiable {
        case clipboard = "Clipboard"
        case newQueryWindow = "New Query Window"
        case file = "Single File"
        var id: String { rawValue }
    }
    var destination: Destination = .newQueryWindow
    
    // Progress
    var isScripting = false
    var progress: Double = 0
    var statusMessage = ""
    var resultScript = ""
    
    private let session: DatabaseSession
    private let logger = Logger(label: "GenerateScriptsWizardViewModel")
    
    init(session: DatabaseSession) {
        self.session = session
    }
    
    func loadObjects() {
        guard let client = session.dependencies else { return }
        isLoadingObjects = true
        
        Task {
            do {
                self.objects = try await client.listAllObjects()
                // Default to select all
                self.selectedObjectIDs = Set(self.objects)
                self.isLoadingObjects = false
            } catch {
                logger.error("Failed to load objects for scripting: \(error)")
                self.isLoadingObjects = false
            }
        }
    }
    
    func generate() {
        guard let client = session.dependencies else { return }
        isScripting = true
        progress = 0
        statusMessage = "Analyzing dependencies..."
        
        Task {
            do {
                let graph = try await client.buildGraph()
                let allSorted = graph.resolvedOrder()
                
                // Filter to only what user selected, but keep topological order
                let sortedSelected = allSorted.filter { selectedObjectIDs.contains($0) }
                
                var finalScript = "-- Generated by Echo on \(Date().formatted())\n"
                finalScript += "USE [\(try await session.currentDatabaseName() ?? "master")];\nGO\n\n"
                
                let total = Double(sortedSelected.count)
                for (index, obj) in sortedSelected.enumerated() {
                    statusMessage = "Scripting \(obj.qualifiedName)..."
                    
                    // In a real implementation, we would call fetchObjectDefinition
                    // and apply formatting options. For the MVP, we use existing APIs.
                    let definition = try await session.getObjectDefinition(
                        objectName: obj.name,
                        schemaName: obj.schema,
                        objectType: mapType(obj.type)
                    )
                    
                    if scriptDropAndCreate {
                        finalScript += "/* DROP logic would go here */\n"
                    }
                    
                    finalScript += definition + "\nGO\n\n"
                    progress = Double(index + 1) / total
                }
                
                self.resultScript = finalScript
                self.statusMessage = "Scripting complete."
                self.isScripting = false
                self.currentStep = .summary
            } catch {
                logger.error("Script generation failed: \(error)")
                self.statusMessage = "Error: \(error.localizedDescription)"
                self.isScripting = false
            }
        }
    }
    
    private func mapType(_ type: String) -> SchemaObjectInfo.ObjectType {
        switch type {
        case "U": return .table
        case "V": return .view
        case "P": return .procedure
        case "FN", "IF", "TF": return .function
        default: return .table // Fallback
        }
    }
    
    func nextStep() {
        if let next = Step(rawValue: currentStep.rawValue + 1) {
            currentStep = next
        }
    }
    
    func prevStep() {
        if let prev = Step(rawValue: currentStep.rawValue - 1) {
            currentStep = prev
        }
    }
}
