/// Every design round, newest first: what it asked, what was decided, and its pages.
@MainActor
enum LabRounds {
    struct Info: Identifiable {
        let id: String
        /// "Round 14".
        let label: String
        let title: String
        let date: String
        /// What the round asked, in plain words.
        let asked: String
        /// What was decided (or where it stands).
        let outcome: String
        /// The round's pages (`LabPage.id`).
        let pageIDs: [String]
        /// A round can cover several topics; each is a line with its outcome.
        var topics: [(title: String, outcome: String)] = []
    }

    static let all: [Info] = [
        // ROUND-INFO (Scripts/new-round.py adds new rounds below this line, newest first)
        Info(id: "r59", label: "Round 59", title: "A card arriving under the pinned menu", date: "2 Oct 2026",
             asked: "Scrolling the tree, the next card arrives under the previous card's pinned menu pill. Show how the hand-over should look: the pill pushed out, fading, overtaken by the next card, shrinking to a name chip, and the cards separate or overlapping with rounded corners and a shadow.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.card-handover-r59"]),
        Info(id: "r58", label: "Round 58", title: "Smaller card headers and what each setting does", date: "2 Oct 2026",
             asked: "The card headers feel too big even at Small with Banner with Title. Show variations that are smaller, and define exactly what each customization does (Line Above the Name = None must be only the name and tight) with the header's heights shown.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.header-sizes-r58"]),
        Info(id: "r57", label: "Round 57", title: "The card header while the list scrolls", date: "2 Oct 2026",
             asked: "When a card's list scrolls, the pinned banner header cuts the rows off with a hard edge and looks bad. Show how the header and the icon menu should behave: rounded bottom corners, the icon menu scrolling away first and then the header, collapsing, or something else.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.header-on-scroll-r57"]),
        Info(id: "r56", label: "Round 56", title: "The connect card, now its own button", date: "2 Oct 2026",
             asked: "The connect button is now its own glass circle under the pills, but its card still opens as if from the top group of active servers. Decide how the card should open from a button of its own, what it holds now that the connected servers are visible beside it, how the button behaves while the card is open, and that clicking outside dismisses it as well as the x.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.connect-card-r56"]),
        Info(id: "r55", label: "Round 55", title: "Trail items: open, minimized and recent servers", date: "2 Oct 2026",
             asked: "The dashed ring for a minimized server looks ugly. Show how a trail item should look when its server is connected and open or connected and minimized, and whether the trail should also show recently connected servers (dimmed, in the same pill or in a second pill) that connect when clicked and move into the active group.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.trail-item-states-r55"]),
        Info(id: "r54", label: "Round 54", title: "Minimizing a card into the trail", date: "2 Oct 2026",
             asked: "Show different animations for how a server card is moved into the server trail when it is minimized (and brought back), since a closed card now leaves the tree and its trail item takes a dashed ring.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.card-to-trail-r54"]),
        Info(id: "r53", label: "Round 53", title: "Server card header: customization and the chevron", date: "2 Oct 2026",
             asked: "Take round 50's chosen header (F5, hairline edge, bold eyebrow over a semibold 22 name, filled selected icon, no underline or pill) and suggest simple customizations to offer users beyond colour and icon colour (fonts, sizes and so on), and show chevron ideas, since today's is too basic and does not animate.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.server-header-custom-r53"]),
        Info(id: "r52", label: "Round 52", title: "The + button: connecting to a server", date: "2 Oct 2026",
             asked: "The + in the server trail opens a context menu below it: too little, a poor way to show saved connections, and a menu under a liquid-glass pill feels off. Explore opening to the right of the +, the + animating into a chevron, and better ways to list saved connections.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.connect-menu-r52"]),
        Info(id: "r51", label: "Round 51", title: "Server trail: telling servers apart, and a shelf for minimized cards", date: "2 Oct 2026",
             asked: "Minimized server cards are opened from the server trail, but the trail's two-letter monograms are too generic to spot a server in under a second. Offer levels of customization for the trail's items, and maybe a place where minimized cards can be retrieved (while keeping that distinct from the trail).",
             outcome: "Being judged.",
             pageIDs: ["ongoing.server-trail-identity-r51"]),
        Info(id: "r50", label: "Round 50", title: "Server card: a header that looks designed", date: "2 Oct 2026",
             asked: "Every server card header from round 30 is about 90% there but still looks AI-made rather than professionally designed: the font, the colours, the placement of items. Explore many more directions to narrow down where the card should go.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.server-header-polish-r50"]),
        Info(id: "r49", label: "Round 49", title: "Tool tabs: every page, calmer switching, icons", date: "2 Oct 2026",
             asked: "Show every page of a tool in its tab (no More menu), make switching tabs smooth, redo the tab icons, and remove the server dot from tabs and the results pill",
             outcome: "Accepted (FP4, MO9, IC1, SD2, PD1; Advanced Objects as four tools) and built into Echo; waiting for the owner to check it in the running app.",
             pageIDs: ["ongoing.tool-tab-bar-r49"]),
        Info(id: "r48", label: "Round 48", title: "Opening, connecting and closing the last tab", date: "1 Oct 2026",
             asked: "Animate the welcome page (the mark alone, echoing in like echodb.dev), the jump from the welcome to a connected server's page, and closing the last tab, which today lands on the welcome instead of the server's page.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.opening-and-closing-r48"]),
        Info(id: "r47", label: "Round 47", title: "Results: the row-number gutter and the column header", date: "1 Oct 2026",
             asked: "The results' row-number column and column header look off (the header's names don't line up with the right-aligned numbers, two lines under the header); make the gutter as good and consistent as the editor's, keeping everything it does.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.results-gutter-r47"]),
        Info(id: "r46", label: "Round 46", title: "Server card: opening and closing", date: "1 Oct 2026",
             asked: "Expanding and collapsing a server card is barebones: the card's edge moves, but the dock and the tree just appear. Look at how switching sections animates and find a proper way to bring in the dock.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.server-card-unfold-r46"]),
        Info(id: "r45", label: "Round 45", title: "Tool tabs: the main action in the toolbar", date: "1 Oct 2026",
             asked: "Main actions such as New Policy or Start Trace / Stop Trace should live in a separate group in the window toolbar, like the Run button or a + sign, and running could use the toolbar's Run button (owner's feedback on 37.3).",
             outcome: "Being judged.",
             pageIDs: ["ongoing.tool-tab-main-action-r45"]),
        Info(id: "r44", label: "Round 44", title: "The blur under the footer", date: "1 Oct 2026",
             asked: "The blur under the results footer still doesn't look smooth: test every way to blur the rows away under the footer and make it look perfect.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.footer-blur-r44"]),
        Info(id: "r43", label: "Round 43", title: "Settings: search, reset and overrides", date: "1 Oct 2026",
             asked: "Make Editor settings the template for every settings page, with a preview for everything that changes something.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.settings-scenarios-r43"]),
        Info(id: "r43", label: "Round 43", title: "Settings: the template on other pages", date: "1 Oct 2026",
             asked: "Make Editor settings the template for every settings page, with a preview for everything that changes something.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.settings-template-r43"]),
        Info(id: "r43", label: "Round 43", title: "Settings: controls and words", date: "1 Oct 2026",
             asked: "Make Editor settings the template for every settings page, with a preview for everything that changes something.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.settings-controls-r43"]),
        Info(id: "r43", label: "Round 43", title: "Settings: a picture for every choice", date: "1 Oct 2026",
             asked: "Make Editor settings the template for every settings page, with a preview for everything that changes something.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.settings-pictures-r43"]),
        Info(id: "r43", label: "Round 43", title: "Settings: the page and its preview", date: "1 Oct 2026",
             asked: "Make Editor settings the template for the other settings pages, and perfect it: every setting that changes something needs a preview (the gutter, for one). An extensive round over every kind of settings scenario.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.settings-preview-r43"]),
        Info(id: "r42", label: "Round 42", title: "Context menus: folders and sections", date: "1 Oct 2026",
             asked: "The best context menus in the world for every object, with extensive rounds.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.context-menu-folder-r42"]),
        Info(id: "r42", label: "Round 42", title: "Context menus: columns, routines and the rest", date: "1 Oct 2026",
             asked: "The best context menus in the world for every object, with extensive rounds.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.context-menu-column-r42"]),
        Info(id: "r42", label: "Round 42", title: "Context menus: tables and views", date: "1 Oct 2026",
             asked: "The best context menus in the world for every object, with extensive rounds.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.context-menu-table-r42"]),
        Info(id: "r42", label: "Round 42", title: "Context menus: database", date: "1 Oct 2026",
             asked: "The best context menus in the world for every object, with extensive rounds.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.context-menu-database-r42"]),
        Info(id: "r42", label: "Round 42", title: "Context menus: server", date: "1 Oct 2026",
             asked: "The best context menus in the world for every object, with extensive rounds.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.context-menu-server-r42"]),
        Info(id: "r42", label: "Round 42", title: "Context menus: the rules", date: "1 Oct 2026",
             asked: "Right-clicking a server, database, table, view, column and everything else should open the best context menus in the world, where everything feels natural to press (Properties at the bottom, maybe). Research the best UX and make extensive rounds.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.context-menu-anatomy-r42"]),
        Info(id: "r41", label: "Round 41", title: "Results: a popover for each footer pill", date: "1 Oct 2026",
             asked: "The results card's header lines, selection summary, error page, Messages panel and footer pill popovers.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.results-pill-popovers-r41"]),
        Info(id: "r41", label: "Round 41", title: "Results: the Messages panel", date: "1 Oct 2026",
             asked: "The results card's header lines, selection summary, error page, Messages panel and footer pill popovers.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.results-messages-r41"]),
        Info(id: "r41", label: "Round 41", title: "Results: the error page and its neighbours", date: "1 Oct 2026",
             asked: "The results card's header lines, selection summary, error page, Messages panel and footer pill popovers.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.results-error-page-r41"]),
        Info(id: "r41", label: "Round 41", title: "Results: the selection summary", date: "1 Oct 2026",
             asked: "The results card's header lines, selection summary, error page, Messages panel and footer pill popovers.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.results-selection-summary-r41"]),
        Info(id: "r41", label: "Round 41", title: "Results: the column header's lines", date: "1 Oct 2026",
             asked: "In the result panel's column headers there seem to be double lines.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.results-header-lines-r41"]),
        Info(id: "r40", label: "Round 40", title: "Clicking a server while the tree is hidden", date: "1 Oct 2026",
             asked: "With the sidebar hidden, clicking a server in the rail opens the glass card we decided on before. I hate it: it should open the sidebar with that server selected.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.rail-click-hidden-tree-r40"]),
        Info(id: "r39", label: "Round 39", title: "Rail tools: Clipboard", date: "1 Oct 2026",
             asked: "Each item in the rail's bottom pill needs a revision in design and function, and a decision on whether it's needed.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.rail-clipboard-r39"]),
        Info(id: "r39", label: "Round 39", title: "Rail tools: History", date: "1 Oct 2026",
             asked: "Each item in the rail's bottom pill needs a revision in design and function, and a decision on whether it's needed.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.rail-history-r39"]),
        Info(id: "r39", label: "Round 39", title: "Rail tools: Snippets", date: "1 Oct 2026",
             asked: "Each item in the rail's bottom pill needs a revision in design and function, and a decision on whether it's needed.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.rail-snippets-r39"]),
        Info(id: "r39", label: "Round 39", title: "Rail tools: Bookmarks", date: "1 Oct 2026",
             asked: "Each item in the rail's bottom pill needs a revision in design and function, and a decision on whether it's needed.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.rail-bookmarks-r39"]),
        Info(id: "r39", label: "Round 39", title: "Rail tools: keep, merge or move", date: "1 Oct 2026",
             asked: "Bookmarks, Snippets, History and Clipboard at the bottom of the rail are leftovers from the old design. Deep dive: are they needed, how should they look and work, and how do they fit the rest of Echo?",
             outcome: "Being judged.",
             pageIDs: ["ongoing.rail-tools-r39"]),
        Info(id: "r38", label: "Round 38", title: "Tree rows that open a tab", date: "1 Oct 2026",
             asked: "Security Management is only reachable by right-clicking Security; make it a row under Security, and add a mark on the right of rows that open a tab, as Agent Jobs Overview does.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.tree-tool-rows-r38"]),
        Info(id: "r37", label: "Round 37", title: "Tool tabs: the tab's own buttons in the toolbar", date: "1 Oct 2026",
             asked: "Whenever a tab has dedicated buttons they go in the toolbar, at the right and to the left of the other icons, and show that they are tied to the tab you have open; the query editor has several groups; Run is special and may look like a regular button. An extensive lab.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.tool-tab-toolbar-r37"]),
        Info(id: "r37", label: "Round 37", title: "Tool tabs: a theme per family", date: "1 Oct 2026",
             asked: "Make a unified design theme for every type of tab window except the query editor.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.tool-tab-themes-r37"]),
        Info(id: "r37", label: "Round 37", title: "Tool tabs: buttons and controls", date: "1 Oct 2026",
             asked: "Make a unified design theme for every type of tab window except the query editor.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.tool-tab-controls-r37"]),
        Info(id: "r37", label: "Round 37", title: "Tool tabs: the header and toolbar row", date: "1 Oct 2026",
             asked: "Make a unified design theme for every type of tab window except the query editor.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.tool-tab-header-r37"]),
        Info(id: "r37", label: "Round 37", title: "Tool tabs: the families", date: "1 Oct 2026",
             asked: "Make a unified design theme for every type of tab window except the query editor: group every other type, give each group a theme, and one theme for all.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.tool-tab-families-r37"]),
        Info(id: "r36", label: "Round 36", title: "Tool tabs with pages: which tools", date: "1 Oct 2026",
             asked: "Introduce the pages everywhere they are needed, e.g. SQL Server Policy Management.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.tool-tab-pages-where-r36"]),
        Info(id: "r36", label: "Round 36", title: "Tool tabs with pages: the tab bar", date: "1 Oct 2026",
             asked: "Activity Monitor's pages in its tab look half-baked: they sit in another pill and look buggy, and with Activity Monitor alone the tab bar looks hideous. Perfect it, and use it everywhere it's needed (Policy Management has nothing yet).",
             outcome: "Being judged.",
             pageIDs: ["ongoing.tool-tab-pages-r36"]),
        Info(id: "r35", label: "Round 35", title: "Tab overview: opening, closing and keys", date: "1 Oct 2026",
             asked: "The tab overview looks hideous; many more suggestions and ways of looking at it.",
             outcome: "Withdrawn: written for the full-window grid, which 35.1 replaced with the ⌘K palette (owner, 1 Oct).",
             pageIDs: ["ongoing.tab-overview-motion-r35"]),
        Info(id: "r35", label: "Round 35", title: "Tab overview: grouping, order and search", date: "1 Oct 2026",
             asked: "The tab overview looks hideous; many more suggestions and ways of looking at it.",
             outcome: "Withdrawn: written for the full-window grid, which 35.1 replaced with the ⌘K palette (owner, 1 Oct).",
             pageIDs: ["ongoing.tab-overview-grouping-r35"]),
        Info(id: "r35", label: "Round 35", title: "Tab overview: the card", date: "1 Oct 2026",
             asked: "The tab overview looks hideous; many more suggestions and ways of looking at it.",
             outcome: "Withdrawn: written for the full-window grid, which 35.1 replaced with the ⌘K palette (owner, 1 Oct).",
             pageIDs: ["ongoing.tab-overview-card-r35"]),
        Info(id: "r35", label: "Round 35", title: "Tab overview: the direction", date: "1 Oct 2026",
             asked: "The tab overview looks hideous and not how I remembered the earlier round. Bring it back with many more suggestions and many different ways of looking at it.",
             outcome: "Accepted: TO6, the palette, as a scope of ⌘K (\"Tab Overview\", ⇧⌘O, the button, a pinch); ⌫ closes, ⌘D duplicates, ⌥⌫ closes the others. Built into Echo (2140dd2f); waiting for your check in the running app.",
             pageIDs: ["ongoing.tab-overview-direction-r35"]),
        Info(id: "r34", label: "Round 34", title: "Refresh and the activity signal", date: "1 Oct 2026",
             asked: "After a query runs, both Run and Refresh show a checkmark; only Run should. Do we still need the Refresh button, and what is it for?",
             outcome: "Being judged.",
             pageIDs: ["ongoing.refresh-and-activity-r34"]),
        Info(id: "r33", label: "Round 33", title: "SQL Server Agent Jobs: New Step", date: "1 Oct 2026",
             asked: "The New Step sheet doesn't look good.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.agent-job-step-sheet-r33"]),
        Info(id: "r33", label: "Round 33", title: "SQL Server Agent Jobs: the tab", date: "1 Oct 2026",
             asked: "The Agent Jobs tab feels 80% done: headers sit in different places and the panes don't line up. I like the general idea; finish it.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.agent-jobs-tab-r33"]),
        Info(id: "r32", label: "Round 32", title: "Panels in dark mode", date: "1 Oct 2026",
             asked: "In dark mode the panels and the background are too similar; it is hard to see what is what.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.panel-fills-dark-r32"]),
        Info(id: "r32", label: "Round 32", title: "Panels: is the inspector whiter?", date: "1 Oct 2026",
             asked: "The inspector, and Details in SQL Server Agent Jobs, feel whiter than the other panels. Is it true? Look for other places too.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.panel-fills-light-r32"]),
        Info(id: "r31", label: "Round 31", title: "Editor: the zoom pill and the footer", date: "1 Oct 2026",
             asked: "The zoom pill sits too far up in the editor; it should sit as close to the editor's bottom as the server pill sits to the results card's. Without results it sits too close to the server pill: align it with the server pill and stack it above, at the same height, with text as bright as the footer's.",
             outcome: "Built into Echo (3626716a), waiting for your check in the running app: 12pt in and 9pt up with results, stacked 9pt above the server pill without, 24pt, primary text.",
             pageIDs: ["ongoing.zoom-pill-footer-r31"]),
        Info(id: "r30", label: "Round 30", title: "Database folders that are empty", date: "1 Oct 2026",
             asked: "Under a database I can no longer find Views.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.empty-folders-r30"]),
        Info(id: "r30", label: "Round 30", title: "Server card: collapsing", date: "1 Oct 2026",
             asked: "The chevron that collapses a server card isn't centred, and collapsing or expanding has no beautiful animation.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.server-header-collapse-r30"]),
        Info(id: "r30", label: "Round 30", title: "Server card: the header", date: "1 Oct 2026",
             asked: "The server card's header feels too quiet: explore headers with more presence, in the server's colour, a custom colour or the accent colour, and other ideas.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.server-header-look-r30"]),
        Info(id: "r29", label: "Round 29", title: "SQL Server: Always Encrypted columns", date: "1 Oct 2026",
             asked: "Echo now learns which SQL Server columns are Always Encrypted but has no keys to decrypt them; how should those columns look and behave in the results grid?",
             outcome: "Being judged.",
             pageIDs: ["ongoing.mssql-always-encrypted-r29"]),
        Info(id: "r28", label: "Round 28", title: "Query editor", date: "1 Oct 2026",
             asked: "Everything about the query editor, decided page by page: the text and its line height, the gutter, the caret, current line and selection, the statement at the caret, highlights and marks, errors, the run note, a new zoom control, find and typing, the empty tab, and which of it stays a setting.",
             outcome: "Built into Echo, waiting for your check in the running app: 28.1 to 28.11 (your picks where they differed: rounded 3pt selection and highlight corners as settings, every gutter surface in Settings, E10 tinted pill with a glass bubble, R10 glass run note with H9 and RR1, prompt only in an empty tab, Aurora and Midnight only). 28.12 to 28.15 too: the glass find bar (FB5) with a Selection button, the replacement shown in the text (PV6) as Replace grows the capsule, the lane centred and full height, and one mark language from tokens (round ends, soft and strong, colour by meaning) with Settings › Editor › Marks.",
             pageIDs: ["ongoing.editor-text-r28", "ongoing.editor-gutter-r28", "ongoing.editor-caret-line-r28", "ongoing.editor-statement-r28", "ongoing.editor-marks-r28", "ongoing.editor-errors-r28", "ongoing.editor-run-note-r28", "ongoing.editor-zoom-r28", "ongoing.editor-find-typing-r28", "ongoing.editor-empty-r28", "ongoing.editor-settings-r28", "ongoing.editor-find-bar-r28", "ongoing.editor-search-replace-r28", "ongoing.editor-gutter-lane-r28", "ongoing.editor-design-language-r28"]),
        Info(id: "r27", label: "Round 27", title: "Results scroll bars and the footer", date: "1 Oct 2026",
             asked: "Where should the results grid's horizontal scroll bar sit so it blends in with the footer instead of floating over the rows above it?",
             outcome: "Being judged.",
             pageIDs: ["ongoing.results-scrollers-r27"]),
        Info(id: "r26", label: "Round 26", title: "Tab content while the tree slides", date: "1 Oct 2026",
             asked: "How should a heavy tab (Activity Monitor's tables) behave while the tree or inspector slides: reflow live, or hold its width and settle at the end?",
             outcome: "Being judged.",
             pageIDs: ["ongoing.content-during-slide-r26"]),
        Info(id: "r25", label: "Round 25", title: "SQL Server: importing a file", date: "30 Sep 2026",
             asked: "Imports into SQL Server now use the TDS bulk load; which of its options should the Import Data sheet offer, and what should a failed import leave behind?",
             outcome: "Being judged.",
             pageIDs: ["ongoing.mssql-import-r25"]),
        Info(id: "r24", label: "Round 24", title: "Run: ▶ into ■", date: "30 Sep 2026",
             asked: "How ▶ transforms into ■ when a query starts, and how the capsule turns red and grows for the timer, smoothly (owner's notes on round 20)",
             outcome: "Accepted: one button in its own glass; ▶ replaced by ■ in place (as round 20's R1), the glass fades to red, then it grows and the time fades in, staged; the red drains as the ✓ draws. Built into Echo; waiting for your check in the running app.",
             pageIDs: ["ongoing.run-into-running-r24"]),
        Info(id: "r23", label: "Round 23", title: "Postgres: several servers and failover", date: "30 Sep 2026",
             asked: "The connection sheet's options for what postgres-wire now supports: Kerberos sign-in, an encrypted client key, several servers with failover.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.pg-failover-hosts-r23"]),
        Info(id: "r23", label: "Round 23", title: "Postgres: encrypted client key", date: "30 Sep 2026",
             asked: "The connection sheet's options for what postgres-wire now supports: Kerberos sign-in, an encrypted client key, several servers with failover.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.pg-client-key-password-r23"]),
        Info(id: "r23", label: "Round 23", title: "Postgres: Kerberos sign-in", date: "30 Sep 2026",
             asked: "The connection sheet's options for what postgres-wire now supports: Kerberos sign-in, an encrypted client key, several servers with failover.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.pg-kerberos-signin-r23"]),
        Info(id: "r22", label: "Round 22", title: "SQL Server: encryption settings", date: "30 Sep 2026",
             asked: "What do Optional, Mandatory and Strict mean now, which is the default, and how does the sheet explain them?",
             outcome: "Being judged.",
             pageIDs: ["ongoing.mssql-encryption-r22"]),
        Info(id: "r22", label: "Round 22", title: "SQL Server: cancel, timeouts and lost connections", date: "30 Sep 2026",
             asked: "Cancel no longer throws the query tab's session away; what changes for cancel, the 45-second limit and a dropped connection?",
             outcome: "Being judged.",
             pageIDs: ["ongoing.mssql-sessions-r22"]),
        Info(id: "r22", label: "Round 22", title: "SQL Server: errors and messages", date: "30 Sep 2026",
             asked: "How should SQL Server errors show their number, severity, state and line, and what does a commit with an unknown outcome say?",
             outcome: "Being judged.",
             pageIDs: ["ongoing.mssql-errors-r22"]),
        Info(id: "r22", label: "Round 22", title: "SQL Server: values in the grid", date: "30 Sep 2026",
             asked: "Values after row 200 of a SQL Server result are garbled, and dates, offsets and money lose digits; how should they read?",
             outcome: "Being judged.",
             pageIDs: ["ongoing.mssql-values-r22"]),
        Info(id: "r21", label: "Round 21", title: "PostgreSQL: sessions, scripts and results", date: "30 Sep 2026",
             asked: "Everything Echo can now do with PostgreSQL that needs a look first: eight pages. Transaction state in a tab, closing or switching with an open transaction, a lost connection, cancelling on the server, script results, where an error is, how PostgreSQL values read in the grid, and statement timeouts.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.pg-transaction-state-r21", "ongoing.pg-open-transaction-guard-r21", "ongoing.pg-connection-lost-r21", "ongoing.pg-cancel-r21", "ongoing.pg-script-results-r21", "ongoing.pg-error-location-r21", "ongoing.pg-value-display-r21", "ongoing.pg-timeouts-r21"]),
        Info(id: "r20", label: "Round 20", title: "Run button", date: "30 Sep 2026",
             asked: "Everything the Run button can be, now that it sits in its own toolbar group: two pages, how it looks at rest (form, icon, colour, selection, hover, unavailable, other modes) and how it moves (running look, a delay for quick queries, timer, stop icon, motion, the change into running, the result). Changes EDT-4.1 to EDT-4.5.",
             outcome: "Accepted: Run stays a plain ▶ at rest; its tooltip says where it runs or why it can't, it never overflows, ⌘↩ toggles Run and Stop; running keeps the red capsule and time (“5 s”), Stopping on a slow cancel, the ✓ draws itself, a notification for long queries while away. The change into running went to round 24. Built into Echo; waiting for your check in the running app.",
             pageIDs: ["ongoing.run-button-look-r20", "ongoing.run-button-running-r20"]),
        Info(id: "r19", label: "Round 19", title: "Section dock", date: "30 Sep 2026",
             asked: "Three pages on the dock as built in round 16: how a card switches sections (and why the card above moves), how the capsule looks, and how many sections a dock holds and what happens to the rest. Changes TREE-1.2 and TREE-3.1 to TREE-3.7.",
             outcome: "Being judged.",
             pageIDs: ["ongoing.section-dock-switching-r19", "ongoing.section-dock-capsule-r19", "ongoing.section-dock-sections-r19"]),
        Info(id: "r18", label: "Round 18", title: "Notification toast", date: "30 Sep 2026",
             asked: "Everything about the toast itself: its layout, actions, dismissing, material, how it arrives, how several stack, and how long it stays.",
             outcome: "Title and detail, small buttons, swipe right to dismiss; glass, drop from the top, a list of three and 3 s kept. Built into Echo; waiting for your check in the running app.",
             pageIDs: ["ongoing.notification-toast-r18"]),
        Info(id: "r17", label: "Round 17", title: "Notification history", date: "30 Sep 2026",
             asked: "How the notification history looks in the inspector's column, and how a notification opens to its whole, selectable message.",
             outcome: "Accepted: D · Compact cards by time, fading in; the count beside the title with one ⋯ menu (H3); small buttons (A2). Built into Echo; waiting for your check in the running app.",
             pageIDs: ["ongoing.notification-history-r17"]),
        Info(id: "r16", label: "Round 16", title: "Server card", date: "30 Sep 2026",
             asked: "Your bugs and feedback on the section dock as built: header and dock styles, the edge under the pinned header, switching, loading, counts, selection, dock customising and PostgreSQL's sections.",
             outcome: "First look: H5 glass capsule, version under the name, blur rows, crossfade, quiet skeleton, counts always, symmetric selection; customising and PostgreSQL's sections kept. Being judged again: H5 as Xcode's navigator icons with rows blurred under the glass, blur rows modelled on the system edge (with a reference), what stays pinned, and five spinner options for the initial load.",
             pageIDs: ["ongoing.server-card-r16"]),
        Info(id: "r15", label: "Round 15", title: "Run, inspector and notifications", date: "30 Sep 2026",
             asked: "Five places for the Run button, three looks for the inspector column, and where toasts and the history live.",
             outcome: "Run is a plain ▶ in its own capsule. The inspector is one card with grouped boxes. Toasts sit at the top right of the first card; the history opens in the inspector's column. Built into Echo (commit 755f8254), waiting for your confirmation.",
             pageIDs: ["ported.Round 15 · Run", "ported.Round 15 · inspector", "ported.Round 15 · notifications"]),
        Info(id: "r14", label: "Round 14", title: "Design board answers", date: "30 Sep 2026",
             asked: "The design board's remaining Maybes drawn on the real tokens, in four topics: tab bar and how a tool's pages open, the section dock and icon style, the connection sheet, and EchoSense selection and corners.",
             outcome: "Answered on 30 Sep; parts are built (the dock and icons), the rest is accepted and waiting to be built.",
             pageIDs: ["ported.Round 14 · tab bar and pages", "ported.Round 14 · section dock", "ported.Round 14 · connections", "ported.Round 14 · EchoSense selection"],
             topics: [
                ("Tab bar and pages", "Round 9's strip on one line; a tool's pages unfold inside its tab (ST2). N1, N1R and N7, and the drawer, tab group, page menu and second bar were rejected."),
                ("Section dock", "TC1 accepted: an icon row under the server's name. Duotone icons by default (IC2), mono line a setting (IC1). Built."),
                ("Connections", "CN5: edit inside Manage Connections, with CN2's short sheet. Rules CR1 to CR7 accepted except CR6."),
                ("EchoSense selection", "Tint while typing, solid once you use the arrows (ESR4); card material with corners following Card Corners (ESR5); rows ES1 and footer ES4; ghost text a setting, off."),
             ]),
        Info(id: "r13", label: "Round 13", title: "New tab bar directions", date: "29 Sep 2026",
             asked: "Three new single-line tab bar directions.",
             outcome: "All rejected; the tab bar went back to Round 9's strip on one line.",
             pageIDs: ["decided.round13-tab-directions"]),
        Info(id: "tree", label: "Tree card round", title: "Server card rows", date: "29 Sep 2026",
             asked: "Six ways to draw the rows inside the server card, beside today's.",
             outcome: "S4 Quiet with folders and a dimmed schema prefix.",
             pageIDs: ["decided.tree-card-s4-quiet"]),
        Info(id: "r12", label: "Round 12", title: "Two-line tabs", date: "29 Sep 2026",
             asked: "Two-line versions of the tab bar.",
             outcome: "T1 with two lines and L2's icon; later replaced by one line in Round 14.",
             pageIDs: ["decided.round12-two-line-tabs"]),
        Info(id: "r11", label: "Round 11", title: "Tab bar", date: "29 Sep 2026",
             asked: "Eight tab bar designs beside today's glass and Classic, after the glass capsule felt weak.",
             outcome: "T1 (Safari) with two lines; later replaced by one line in Round 14.",
             pageIDs: ["decided.round11-tab-bar"]),
        Info(id: "r10", label: "Round 10", title: "Footer, switcher, results and inspector", date: "29 Sep 2026",
             asked: "How the footer's right side looks, how the database switcher opens, how results enter, whether to keep the pinned header, and where the inspector goes.",
             outcome: "A glass pill per entry; a card above the chip that rises; results grow out of the footer; pinned header removed; inspector as a column of cards.",
             pageIDs: ["decided.round10-footer-and-switcher", "decided.inspector-column"]),
        Info(id: "r9", label: "Round 9", title: "Footer, scroll bar and tabs", date: "29 Sep 2026",
             asked: "What sits behind the footer, where the footer sits, whether the tree shows a scroll bar, and how the tab bar looks.",
             outcome: "Soft blur behind the footer, lifted 4pt, no tree scroll bar, a glass tab bar (later replaced).",
             pageIDs: ["decided.round9-footer-scroller-tabs"]),
        Info(id: "r3-8", label: "Rounds 3 to 8", title: "Canvas, cards, rail and results", date: "29 Sep 2026",
             asked: "How the window is built: the canvas, the server rail, opaque tree cards, the pinned header, results and notifications.",
             outcome: "A canvas with opaque cards, 16pt corners, a rail with a + and a liquid selection, glass only on controls.",
             pageIDs: ["decided.window-canvas-and-cards", "decided.rail-servers", "decided.tree-sticky-header", "decided.results-grid", "decided.toasts-and-notifications"]),
    ]

    static func info(forPage id: String) -> Info? { all.first { $0.pageIDs.contains(id) } }
}
