import SwiftUI

/// Round 20 · Run button, page 1: how Run looks at rest, now that it sits in its own toolbar group.
/// Every exhibit runs the same simulated query, and the proposal also takes page 2's running
/// choices, so you judge the whole button. Changes EDT-4.1, EDT-4.2 and EDT-4.5.
@MainActor
enum RunButtonLookRound {
    static let spec = RoundSpec(
        controls: [
            .of("form", "Form", LabRBForm.self, default: .plainGlyph,
                question: "Try each form in the Proposal (or line them up with Compare: Forms). Which shape should Run have at rest?",
                recommend: .plainGlyph,
                why: "You chose a quiet ▶ like its neighbours in round 15 and turned down the accent glass as too loud. The worded forms cost 40 to 90pt of toolbar for a button you learn in a day; prominent glass, the disc and the round button make Run the loudest thing in the window all day, though you use it in bursts. The round button is the closest runner-up.",
                summary: \.summary),
            .of("icon", "Icon", LabRBIcon.self, default: .playFill,
                question: "Look at the Icons and colours exhibit, then the Proposal. Which symbol says Run?",
                recommend: .playFill,
                why: "▶ is what Xcode, SSMS, DataGrip and every media player use, so nobody has to learn it. The outline ▷ reads as disabled next to a filled ■; circled and squared ▶ look like media controls; ⚡ suggests automation and the paper plane means Send."),
            .of("colour", "Colour", LabRBColour.self, default: .primary,
                question: "Switch the colour with Text selected on and off, and run a query. Which colour should ▶ have at rest?",
                recommend: .primary,
                why: "macOS toolbar glyphs are monochrome, and Run already uses colour for state: accent for a selection, red while running, green or red for the result. A green ▶ collides with the green ✓; accent loses the selection signal. The server's colour is interesting for production servers, but it belongs to the connection, not to Run.",
                summary: \.summary),
            .of("selection", "Selection signal", LabRBSelection.self, default: .accentGlyph,
                question: "Set the editor to Text selected and back. How should Run say it will run only the selection?",
                recommend: .accentGlyph,
                why: "It shows before you press, and nothing widens. The dot is easy to miss at toolbar size; the words make the capsule grow and push Format's capsule; tooltip only means you find out after the query ran.",
                summary: \.summary),
            .of("hover", "Hover", LabRBHover.self, default: .none,
                question: "Hover Run and its neighbours. Should Run react to the pointer?",
                recommend: .none,
                why: "Its neighbours don't, so Run growing or tinting alone makes it the odd one in the toolbar. If you want the section dock's grow here, it should apply to every toolbar glyph. ⌘↩ sliding out teaches the shortcut but pushes the capsules next to it on every hover.",
                summary: \.summary),
            .of("unavailable", "When it can't run", LabRBUnavailable.self, default: .dimmedReason,
                question: "Set the editor to Empty editor, then Not connected. Hover and click Run in each option. What should Run do?",
                recommend: .dimmedReason,
                why: "Dimmed is what macOS does for a command that can't run, and the tooltip gives the reason, so it is never silently disabled (your rule CR1 for connections). Hiding it moves the capsules beside it; staying on and explaining on a click is friendly, but makes Run look ready when it isn't."),
            .of("menu", "Other modes", LabRBMenu.self, default: .rightClick,
                question: "Open the other modes in each option (right-click still works in all of them). Where should Statement at Cursor and Explain live?",
                recommend: .rightClick,
                why: "You turned down the chevron in round 15; the modes are also in the Query menu with their shortcuts, which is where people look. Click and hold is native (Safari's Back) but invisible; a chevron that appears on hover widens the capsule under the pointer.",
                summary: \.summary),
            .of("memory", "Last mode", LabRBMemory.self, default: .alwaysRun,
                question: "Pick Explain from Run's menu, then click Run again. Should the button remember the mode?",
                recommend: .alwaysRun,
                why: "⌘↩ is always Run, so a button that has silently turned into Explain surprises you. Xcode can do it because its actions are long-lived schemes; here a mode is a one-off.",
                summary: \.summary),
            .of("compare", "Compare", LabRBCompareRest.self, default: .form),
            .of("editor", "Editor", LabRBEditorState.self, default: .ready),
            .of("speed", "Speed", LabSpeed.self, default: .standard),
        ],
        actions: [
            .init(id: "run", title: "Run or cancel", symbol: "play.fill") { _ in LabRBSimulation.shared.toggle() },
            .init(id: "finish", title: "Finish now", symbol: "flag.checkered") { _ in LabRBSimulation.shared.finish() },
        ],
        exhibits: [
            .init(id: "today", title: "Echo today",
                  summary: "QueryRunToolbarControl: a plain ▶ in its own capsule, accent with a selection, dimmed when it can't run, modes on right-click.",
                  isEchoToday: true, designWidth: LabRBToolbarExhibit.width, designHeight: LabRBToolbarExhibit.height) { values in
                LabRBToolbarExhibit(look: .today, values: values)
            },
            .init(id: "proposal", title: "Proposal",
                  summary: "Built from this page's controls, running as page 2 sets it.",
                  designWidth: LabRBToolbarExhibit.width, designHeight: LabRBToolbarExhibit.height) { values in
                LabRBToolbarExhibit(look: .proposal(), values: values)
            },
            .init(id: "compare", title: "Side by side",
                  summary: "Every choice of the control named in Compare, each a live Run with the rest of the proposal.",
                  designWidth: LabRBGalleryExhibit.width, designHeight: LabRBGalleryExhibit.height) { values in
                LabRBGalleryExhibit(rows: (LabRBCompareRest(rawValue: values["compare"]) ?? .form).rows(.proposal()), values: values)
            },
            .init(id: "icons", title: "Icons and colours",
                  summary: "Every icon in every colour, at rest, in the proposal's form. The ring marks the current pair.",
                  designWidth: LabRBIconGridExhibit.width, designHeight: LabRBIconGridExhibit.height) { _ in
                LabRBIconGridExhibit(base: .proposal())
            },
        ],
        questions: [
            .init(id: "otherTabs", title: "Other tabs",
                  question: "Run shows only on query tabs today. What should its group do on a table, a job or a monitor tab?",
                  choices: [
                      .init(id: "hidden", name: "O0 · Hidden (today)", summary: "The group melts away; the tab's own tools show beside it."),
                      .init(id: "dimmed", name: "O1 · Stays, dimmed", summary: "The toolbar never changes shape between tabs."),
                      .init(id: "tabAction", name: "O2 · The tab's main action", summary: "Start Job, Refresh, Apply: one button that always does the obvious thing."),
                  ],
                  recommended: "hidden",
                  why: "You decided each tab's tools form one capsule next to Run that melts in and out; a dimmed Run on a job tab is clutter, and a Run that means Start Job on one tab and Refresh on another can't be learned."),
            .init(id: "runWhileRunning", title: "⌘↩ while running",
                  question: "A query is running and you press ⌘↩ again (or click where ▶ was). What should happen?",
                  choices: [
                      .init(id: "nothing", name: "W0 · Nothing (today)", summary: "Run can't run while the tab is running; the click on ■ cancels."),
                      .init(id: "restart", name: "W1 · Cancel and run again", summary: "Like Xcode: the new run replaces the old one."),
                      .init(id: "ask", name: "W2 · Ask", summary: "“Cancel the running query and run again?”"),
                  ],
                  recommended: "nothing",
                  why: "Pressing ⌘↩ twice by accident should never cancel a long update halfway. Restarting is handy for SELECTs but dangerous for writes; asking interrupts the common case."),
        ],
        exhibitTopic: ("Which Run at rest?",
                       "Try both toolbars with every editor state, run, and open the modes. Is the proposal better than Echo today?",
                       "proposal",
                       "It keeps today's quiet ▶ and its selection accent, and adds the reason to the tooltip when Run can't run. Everything else here costs width or attention."),
        presets: [
            .init(id: "recommended", name: "My recommendation", summary: "F0, ▶, label colour, accent selection, no hover, dimmed with a reason, right-click, always Run.",
                  values: ["form": LabRBForm.plainGlyph.rawValue, "icon": LabRBIcon.playFill.rawValue, "colour": LabRBColour.primary.rawValue,
                           "selection": LabRBSelection.accentGlyph.rawValue, "hover": LabRBHover.none.rawValue,
                           "unavailable": LabRBUnavailable.dimmedReason.rawValue, "menu": LabRBMenu.rightClick.rawValue,
                           "memory": LabRBMemory.alwaysRun.rawValue],
                  isRecommended: true),
            .init(id: "today", name: "Like Echo today", summary: "Every control as Echo draws Run now.",
                  values: ["form": LabRBForm.plainGlyph.rawValue, "icon": LabRBIcon.playFill.rawValue, "colour": LabRBColour.primary.rawValue,
                           "selection": LabRBSelection.accentGlyph.rawValue, "hover": LabRBHover.none.rawValue,
                           "unavailable": LabRBUnavailable.dimmed.rawValue, "menu": LabRBMenu.rightClick.rawValue,
                           "memory": LabRBMemory.alwaysRun.rawValue]),
            .init(id: "ssms", name: "Like SSMS", summary: "A green ▶ with the word, a split menu.",
                  values: ["form": LabRBForm.iconTitle.rawValue, "icon": LabRBIcon.playFill.rawValue, "colour": LabRBColour.green.rawValue,
                           "selection": LabRBSelection.words.rawValue, "hover": LabRBHover.none.rawValue,
                           "unavailable": LabRBUnavailable.dimmed.rawValue, "menu": LabRBMenu.chevron.rawValue,
                           "memory": LabRBMemory.alwaysRun.rawValue]),
            .init(id: "xcode", name: "Like Xcode", summary: "A plain ▶ that remembers the last action, modes on hold.",
                  values: ["form": LabRBForm.plainGlyph.rawValue, "icon": LabRBIcon.playFill.rawValue, "colour": LabRBColour.primary.rawValue,
                           "selection": LabRBSelection.tooltipOnly.rawValue, "hover": LabRBHover.none.rawValue,
                           "unavailable": LabRBUnavailable.dimmed.rawValue, "menu": LabRBMenu.hold.rawValue,
                           "memory": LabRBMemory.lastMode.rawValue]),
            .init(id: "bold", name: "Bold", summary: "Accent prominent glass that grows on hover.",
                  values: ["form": LabRBForm.prominent.rawValue, "icon": LabRBIcon.playFill.rawValue, "colour": LabRBColour.accent.rawValue,
                           "selection": LabRBSelection.dot.rawValue, "hover": LabRBHover.grow.rawValue,
                           "unavailable": LabRBUnavailable.explains.rawValue, "menu": LabRBMenu.hoverChevron.rawValue,
                           "memory": LabRBMemory.alwaysRun.rawValue]),
            .init(id: "media", name: "Media player", summary: "A disc in the capsule, ⌘↩ sliding out on hover.",
                  values: ["form": LabRBForm.disc.rawValue, "icon": LabRBIcon.playFill.rawValue, "colour": LabRBColour.accent.rawValue,
                           "selection": LabRBSelection.dot.rawValue, "hover": LabRBHover.reveal.rawValue,
                           "unavailable": LabRBUnavailable.dimmedReason.rawValue, "menu": LabRBMenu.rightClick.rawValue,
                           "memory": LabRBMemory.alwaysRun.rawValue]),
        ]
    )
}
